version: 2.1
jobs:
  ci:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Run Unit Tests
          command: |
            npm ci
            npm run build
      - persist_to_workspace:
          root: .
          paths:
            - dist/*

workflows:
  version: 2
  ci:
    jobs:
      - ci:
          filters:
            tags:
              only:
                 /.*/
